# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://methods-field-ecology.netlify.com/"
languageCode = "en-AU"
title = "Methods in Field Ecology"

# Metadata
[params]
  author = "Methods in Field Ecology"
  description = ""

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/1.png"
  title = ""
  description = ""

# Navigation section
[params.nav]
  mission = "Scope"
  services = "Apply now"
  team = "The Team"
  contact = "Get in touch"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/Ibitipoca.jpg"
    [[params.mission.images.list]]
      img = "images/regua2.jpg"
    [[params.mission.images.list]]
      img = "images/regua1.jpg"
    [[params.mission.images.list]]
      img = "images/doce1.jpg"

  [[params.mission.item]]
    weight = 1
    name = "Scope"
    title = "Scope"
    subtitle = "The course aims for a deep scientific experience in field Ecology."
    description = "Students will have the opportunity to deepen their skills across different stages of the scientific reasoning: (i) elaborate questions and hypothesis; (ii) design experiments and surveys; (iii) sample data in the field; (iv) analyze their results and (v) write scientific reports. Further, the course will offer an intense experience in tropical ecosystems and a great opportunity for students to strengthen their teamwork skills within an international group of students and mentors.</p><ul class='checked'><li>Learn fundamental methods in field ecology</li><li>Deepen scientific reasoning</li><li>Increase understanding of Tropical Ecosystems</li><li>Strengthen teamwork skills</li></ul><p> <a href='images/Program_MFE.pdf' target = 'blank' class = 'btn btn-primary btn-outline'>PROGRAM</a></p> <p> <a href='https://forms.gle/xc4n1MAe9Cfff45s8' target = 'blank' class = 'btn btn-primary btn-outline'>Apply Now</a></p>"

  #[[params.mission.item]]
  #  weight = 0
  #  name = "Skills"
  #  title = "Skills"
  #  subtitle = ""

  #[[params.mission.item]]
  #  weight = 0
  #  name = "Team work"
  #  title = "team Work"
  #  subtitle = ""
  #  description = "<p>Further, the course will offer an intense experience in tropical ecosystems and a great opportunity for students to strengthen their teamwork skills within an international group of students and mentors.</p>"

# Services section
[params.services]
  enable = true
  video = false
  vidlink = ""
  title = ""
  description = "<p> <a href='https://forms.gle/xc4n1MAe9Cfff45s8' target = 'blank' class = 'btn btn-primary btn-outline'>Apply Now</a></p><p>The course will offer an intense experience in tropical ecosystems and a great opportunity for students to strengthen their teamwork skills within an international group of students and mentors. </p>"

  [[params.services.item]]
    icon = "icon-info"
    title = "Methods"
    description = "Learn fundamental methods in field ecology."

  [[params.services.item]]
    icon = "icon-question"
    title = "Reasoning"
    description = "Deepen scientific reasoning (hypothesis, design, sampling, writing)."
    
  [[params.services.item]]
    icon = "icon-globe"
    title = "Nature"
    description = "Increase understanding of Tropical Ecosystems."
  
# Work section
[params.work]
  enable = false

  [[params.work.item]]
    title = "Parque Estadual do Rio Doce"
    subtitle = "Study Sitei 5"
    img = "images/doce1.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_4.jpg"

# Team section
[params.team]
  enable = true
  title = "Meet The Course Instructors"
  description = ""

  [[params.team.item]]
    name = "Leonardo H. Teixeira (TUM)"
    position = "PhD in Ecology"
    description = "Restoration ecology and biodiversity and ecosystem functioning <p> <a href='http://www.roek.wzw.tum.de/index.php?id=226' target = 'blank'>Website</a></p>"
    img = "images/leonardo.jpg"

  [[params.team.item]]
    name = "Nathan  O. Barros (UFJF)"
    position = "PhD in Ecology"
    description = "<p>Limnology, aquatic ecosystems and microbial ecology</p> <p> <a href='https://scholar.google.com/citations?hl=en&user=CwKsLgEAAAAJ' target = 'blank'>Website</a></p>"
    img = "images/nathan.jpg"
    
    [[params.team.item]]
    name = "Gustavo B. Paterno (UFRN)"
    position = "PhD in Ecology"
    description = "Plant Ecology and Evolution <p> <a href='https://paternogbc.netlify.com' target = 'blank'>Website</a></p>"
    img = "images/gustavo.jpg"

      [[params.team.item]]
    name = "Fabrício Alvim (UFJF)"
    position = "PhD in Ecology"
    description = "Plant and community ecology <p> <a href='https://scholar.google.com.br/citations?user=cnmTS8cAAAAJ&hl=pt-BR' target = 'blank'>Website</a></p>"
    img = "images/fabricio.jpg"

         [[params.team.item]]
    name = "André Megali  (UFJF)"
    position = "PhD in Ecology"
    description = "Ecosystem ecology <p><a href='http://www.ufjf.br/limnologia-eng/staff/actual/professors/666-2/' target = 'blank'>Website</a></p>"
    img = "images/andre.jpg"

            [[params.team.item]]
    name = "Luiz Menini Neto  (UFJF)"
    position = "PhD in Biology"
    description = "Botany, Biogeography and Floristics<p><a href='https://scholar.google.com.br/citations?user=a9ctS0gAAAAJ&hl=pt-BR' target = 'blank'>Website</a>"
    img = "images/menini.jpg"

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   email = "#"
  #   telephone = "#"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"
  #   whatsapp = "#"

# Contact section
[params.contact]
  enable = false
  title = "Get in Touch"
  message = ""
  name_placeholder = "Your name"
  email_placeholder = "Your email"
  email_disclaimer = "We'll never share your email with anyone else."
  message_placeholder = "Please enter a message."
  button_text = "Submit"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2016 Free HTML5 Template. All Rights Reserved. <br> Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> Demo Images: <a href='http://pexels.com/' target='_blank'>Pexels</a><br>Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a></small></p>  </p>"
